version: "3"
services:
  backend:
    container_name: gazeaudio-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/user/app
      - /usr/app/node_modules
    environment:
      - PORT=3000
    ports: ["3000:3000"]
    links:
      - mongo

  frontend:
    container_name: gazeaudio-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://localhost/

  mongo:
    container_name: gazeaudio-database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always
