version: "3"
services:
  server:
    container_name: gazeaudio-server
    image: gazeaudio-server
    build:
      context: ./server
      args:
        - PORT=${SERVER_PORT}
    environment:
      # General
      - HOST=${HOST}
      - ENDPOINT=${ENDPOINT}
      # Eye tracker specifics
      - GAZEPOINT_ADDRESS=${GAZEPOINT_ADDRESS}
      - GAZEPOINT_PORT=${GAZEPOINT_PORT}
      # Database specifics
      - DB_NAME=${DB_NAME}
      - DB_URI=mongodb://mongo:${MONGO_PORT}/${DB_NAME}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    links:
      - mongo
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "npm", "run", "start"]
      interval: 10s
      timeout: 15s
      retries: 5
    restart: on-failure

  client:
    container_name: gazeaudio-client
    image: gazeaudio-client
    build:
      context: ./client
      args:
        - PORT=${CLIENT_PORT}
        - VUE_APP_API_BASE_URL=http://localhost:${SERVER_PORT}${ENDPOINT}
        - VUE_APP_PATH_TO_AUDIO_FOLDER=/webapp/client/src/assets/audio/
        - VUE_APP_PATH_TO_IMAGES_FOLDER=/webapp/client/src/assets/images/
    volumes:
      - ./client/src/assets:/webapp/client/assets
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      - VUE_APP_PATH_ADD_TRIAL=${VUE_APP_PATH_ADD_TRIAL}
      - VUE_APP_PATH_RUN_TRIAL=${VUE_APP_PATH_RUN_TRIAL}
      - VUE_APP_PATH_PREVIEW_TRIAL=${VUE_APP_PATH_PREVIEW_TRIAL}
      - VUE_APP_PATH_TRIAL_RESULTS=${VUE_APP_PATH_TRIAL_RESULTS}
    logging:
      driver: none
    depends_on:
      - server

  mongo:
    container_name: gazeaudio-database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - DB_URI= mongodb://mongo:${MONGO_PORT}/${DB_NAME}
    logging:
      driver: none
    restart: always
