version: "3"
services:
  server:
    container_name: gazeaudio-server
    build:
      context: ./server
    volumes:
      - ./server:/user/app
      - /usr/app/node_modules
    environment:
      - PORT=3000
    ports: ["3000:3000"]
    links:
      - mongo

  client:
    container_name: gazeaudio-client
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://localhost/

  mongo:
    container_name: gazeaudio-database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always
