version: "3"
services:
  server:
    container_name: gazeaudio-server
    build:
      context: ./server
    volumes:
      - ./server:/user/app
      - /usr/app/node_modules
    environment:
      # General
      - PORT=${SERVER_PORT}
      - ENDPOINT=${ENDPOINT}
      # Eye tracker specifics
      - HOST=${HOST}
      - GAZEPOINT_PORT=${GAZEPOINT_PORT}
      # Database specifics
      - DB_NAME=${DB_NAME}
      - DB_URI=mongodb://mongo:${MONGO_PORT}/${DB_NAME}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    links:
      - mongo
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "npm", "run", "start"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

  client:
    container_name: gazeaudio-client
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:${SERVER_PORT}${ENDPOINT}
      - VUE_APP_PATH_TO_AUDIO_FOLDER=/app/src/assets/audio/
      - VUE_APP_PATH_TO_IMAGES_FOLDER=/app/src/assets/images/
    logging:
      driver: none
    depends_on:
      - server

  mongo:
    container_name: gazeaudio-database
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - DB_URI= mongodb://mongo:${MONGO_PORT}/${DB_NAME}
    restart: always
